SoftwareGuide/Latex/Introduction/Installation.tex
Add a cross compilation section following the discussion in
http://review.source.kitware.com/#/c/22681/
Change-Id: Icd02cf8d550924261dcc1776296764d5e600b45e
=> DOC: Add a cross compilation section to Configuring and Building ch.

SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Add content to the empty example in `Variable Initialization` subsection.
Change-Id: I7c8696a8d24119c7a6d0920747454af8412d8d48
=> DOC: Add content to empty example in Variable Initialization

SoftwareGuide/Examples/CMakeLists.txt
Change-Id: Ib4ee309262ada1f5bd076d0f9927729d67afbdfc
=> ENH: Improve EPS conversion operation output

SoftwareGuide/Latex/03-Abstract-Common.tex
Mention at least once, at the beginning, the ITK full name:
`National Library of Medicine Insight Segmentation and Registration
Toolkit`
Change-Id: Ibe2c5d8ceaed026f1e7f04d5a1f488719ded78a5
=> DOC: Mention the ITK full name in common abstract.

Latex/Insight.sty, SoftwareGuide/Latex/Introduction/Installation.tex
Update supported compilers' list according to:
https://itk.org/Wiki/ITK_Release_4/Modern_C++#Fully_Committed_to_Support
Change-Id: Ie09e08249bc45804391b640fd75f80af1d39502e
=> DOC: Update supported compilers' list.

SuperBuild/External_ITK.cmake
Addresses some line length issues.
Also, switch to GitHub repository URL.
Change-Id: I534f5a8bbac398bbb427c861b8e003b41611cd7e
=> BUG: Update ITK version to 2017-12-15 master

.circleci/config.yml
Change-Id: If5c1286fd3ad3ca2073ab78083fe08d0fe06d539
=> ENH: Add CircleCI configuration

SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Add a test layout subsection to develop the layout of unit tests in ITK.
Change-Id: I9734932cf63bacab48d433a0b139b8bfaa584ce3
=> DOC: Add a test layout subsection.

SuperBuild/External_ITK.cmake
Change-Id: I6f39ff27968616eec5a9e26ccad03aad0b23213b
=> ENH: Bump ITK version to 4.13.0

.circleci/config.yml
We do not run any tests.
Change-Id: I0e8332202722523acbddfdf32842563827ef8761
=> BUG: Remove 'test' from the CircleCI build name

SoftwareGuide/Latex/Introduction/Installation.tex
Improved documentation and comments regarding compiler support.  More work is needed here, but this is a nice starting point.
=> Update supported compilers list

SoftwareGuide/Latex/Architecture/DataRepresentation.tex
Fix typo: change "substract" to "subtract".
Change-Id: I598fcd28c4eda00502a07b77d8c0afdcf9673d6f
=> DOC: Fix typo: substract to subtract

Latex/gitdags.sty, SoftwareGuide/Latex/00-Preamble-Common.tex, SoftwareGuide/Latex/Appendices/GitWorkflow.tex, SoftwareGuide/Latex/DevelopmentGuidelines/SoftwareProcess.tex, SoftwareGuide/Latex/ITKSoftwareGuide-Book1.tex
Add a Community Software Process appendix chapter to the ITK SW Guide
following the discussion in:
http://review.source.kitware.com/#/c/22654/
Change-Id: I53ba17103c3afb90987fc4f758b7128b198e31f3
=> DOC: Add a Community Software Process appendix chapter.

Utilities/GitSetup/github-tips, Utilities/SetupForDevelopment.sh
Suggested-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
=> DOC: Suggest git pr, hub, git series, on SetupForDevelopment.sh

README.md
Add the CircleCI badge to the ITK SW Guide GitHub home.
Resolves #53.
=> DOC: Add the CircleCI badge.

Utilities/GitSetup/git-pr
Detect Python 3 when only the python executable is available.
=> ENH: Improve git pr detection of Python 3 when python3 not available

SoftwareGuide/Latex/Introduction/Introduction.tex
Add a note about patented code to the introduction.
=> DOC: Add note about patented code to the introduction.

SoftwareGuide/Latex/Architecture/SystemOverview.tex, SoftwareGuide/Latex/DevelopmentGuidelines/WriteAFilter.tex
=> ENH: adding documentation for refactored multi-threading infrastructure

SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Add a note about direct vs. macro call ivar initialization motivated by
the discussion in:
http://review.source.kitware.com/#/c/23434
=> DOC: Add a note about direct vs. macro call ivar initialization.

Utilities/Hooks/commit-msg
=> ENH: Reference GitHub issue tracker in pre-commit message

SuperBuild/External_ITK.cmake
Build has been pushed to itk.org:
https://itk.org/ITKSoftwareGuide/html/
=> ENH: Bump ITK to 5.0a02

SuperBuild/External_ITK.cmake
Prefer to use the release branch for the software guide.
=> Use release branch for ITKSoftwareGuide

CONTRIBUTING.md
=> DOC: Add reference to ITK's CONTRIBUTING.md

SoftwareGuide/Examples/CMakeLists.txt, SuperBuild/External_ITK.cmake
Also add required fix to output specification for
ShapeDetectionLevelSetFilter.
@hjmjohnson will merge this, then update our Docker images so we have CI testing working again.
=> ENH: Bump ITK version to 5.0 Beta 3

SuperBuild/External_ITK.cmake
Addresses:
Examples/RegistrationITKv4/DeformableRegistration2.cxx:317:80:
warning: Line length too long for LaTeX printing
=> COMP: Bump ITK to address line length warnings

SoftwareGuide/Latex/Appendices/GitWorkflow.tex
=> COMP: Fix too long line lengths

SuperBuild/External_ITK.cmake
Local build succeeds without issue.
=> ENH: Bump ITK version to v5.1rc01

SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
Add section about tests for Wrapping files.
=> ENH: Add section about tests for Wrapping files

.github/workflows/build.yml
=> BUG: Use https protocol for superbuild CI

SuperBuild/External_ITK.cmake
=> ENH: Bump ITK Superbuild version to 5.4 RC 2

SuperBuild/External_ITK.cmake
=> ENH: Bump ITK Superbuild version to 5.4 RC 3

SuperBuild/External_ITK.cmake
=> ENH: Bump ITK Superbuild version to 5.4 RC 4

.github/workflows/build.yml
=> COMP: Bump actions versions

.github/workflows/build.yml
Make this closer to what is used in releases.
=> ENH: Improve Actions PDF artifact name

SuperBuild/External_ITK.cmake
=> ENH: Bump ITK to v5.4.2

SuperBuild/External_ITK.cmake
=> ENH: Bump ITK to v5.4.3

SuperBuild/External_ITK.cmake
=> COMP: Bump ITK to 6.0 Beta 1
