- CMake/CTestCustom.cmake.in
- SuperBuild.cmake
- SuperBuild/External_ITK.cmake
This will facilitate Nightly builds / testing against ITK master.
Change-Id: If867a0df25b89aefd43fe2eb97cf38547dacac87
> ENH: Enable specification of ITK_GIT_TAG in the superbuild

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
The `CMake Style` section was not being listed in the `Overview` section.
Change-Id: I547ab74c31a9e71128200eb856f470289de5f0d4
> DOC: Add a CMake Style item to the Overview section.

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Add a `Documentation Style` section, following the discussion in
Change Id: 22691. In fact, it had been foreseen in the `Overview` section
in previous versions of the Coding Style Guide.
Change-Id: Ic9b938e51f53880e6605f454df2183cf443aeb3a
> DOC: Add Documentation Style section.

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Fix Coding Style Guide formatting/rendering issues:
- Improve rendering of literal code: add blank lines to place literal code
on a line of its own (e.g. in subsec `B.6.3  Naming Classes`)
- Remove redundant `itk` prefix to classes (e.g.
`itk::itkTobogganImageFilter` in subsec `Naming Tests`)
- Break too long literal code blocsk (e.g. `B.6.17 Preprocessor
Directives`).
Change-Id: I7cbfba463d825b6fb778128f94ee57ee6b934ff4
> DOC: Fix Coding Style Guide formatting issues.

- SoftwareGuide/Latex/DesignAndFunctionality/Filtering.tex
Make the ITK long name used in the SW Guide (Insight Toolkit) be consistent
concerning its case: change `Insight toolkit` for `Insight Toolkit`.
Change-Id: Icd004cf94bf8fc04c314100f05d7ac82fad24f1b
> DOC: Fix ITK long name case mismatch.

- SoftwareGuide/Cover/README.md
- SoftwareGuide/Cover/README.txt
- SoftwareGuide/Latex/README.md
Transition `SoftwareGuide/Cover` and `SoftwareGuide/Latex` folder
README.txt files to Markdown.
Use Markdown syntax highlighting.
Change-Id: Ib6faf1ca09b09baf4c96bcb35acf2df8600e7fcf
> DOC: Transition SoftwareGuide/Cover and Latex READMEs to Markdown

- SoftwareGuide/Latex/00-Preamble-Common.tex
This addresses the build error:
! LaTeX Error: Undefined color `shadecolor'.
on Debian 9 (Stretch).
Change-Id: I2a0badc9450706ec031df609f4aaa105293cd6b0
> COMP: Use the xcolor package instead of color

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Conform to to point 8 in SW Guide Style Guidelines when referencing other
sections: use tilde to connect the name and the reference to avoid bad
page breaks.
White space correction.
Change-Id: I267c2cabb1297c8b3b2c7495135f7d215b03ad90
> DOC: Use tilde to connect names and references.

- README.md
Fix ParseCXXExamples.py script location in README.md file.
Looks like commit ee89a28ec2f0b9276f931023ad1184a46cb5e28b overwrote the
previous path renaming done in commit 6541f4781346efaeaaa90de1ca3f4b040eca9687
Change-Id: I3563baf27ffc43de16408e25b68705ad3b4ecc35
> DOC: Fix ParseCxxExamples.py script location in README.md.

- SoftwareGuide/Latex/Architecture/ImageAdaptors.tex
- SoftwareGuide/Latex/DesignAndFunctionality/ConfidenceConnectedOnBrainWeb.tex
- SoftwareGuide/Latex/DesignAndFunctionality/DeformableRegistration.tex
- SoftwareGuide/Latex/DesignAndFunctionality/DeformableRegistration4OnBrain.tex
- SoftwareGuide/Latex/DesignAndFunctionality/HybridSegmentationMethods.tex
- SoftwareGuide/Latex/DesignAndFunctionality/IO.tex
- SoftwareGuide/Latex/DesignAndFunctionality/ImageInterpolators.tex
- SoftwareGuide/Latex/DesignAndFunctionality/ModelBasedRegistration.tex
- SoftwareGuide/Latex/DesignAndFunctionality/Optimizers.tex
- SoftwareGuide/Latex/DesignAndFunctionality/Registration.tex
- SoftwareGuide/Latex/DesignAndFunctionality/Transforms.tex
- SoftwareGuide/Latex/DesignAndFunctionality/VisualizingDeformationFieldsUsingParaview.tex
According to the following LaTeX recommendations, `\centering` should be
used, rather than `\center` or `\begin{center}...\end{center}` which may
have undesired side-effects:
http://texblog.net/latex-archive/floats/center-centering/
https://tex.stackexchange.com/questions/23650/when-should-we-use-begincenter-instead-of-centering
https://tex.stackexchange.com/questions/2651/should-i-use-center-or-centering-for-figures-and-tables
Change-Id: I171a7866ac1fb00271ccc756c71a9dc8cb349564
> DOC: Fix use of \center vs. \centering in figures.

- .circleci/config.yml
Change-Id: I758d9812416d4df2c6153ce4a2a69142fe258c4e
Suggested-by: Bradley Lowekamp <blowekamp@mail.nih.gov>
> ENH: Use ccache in the CircleCI build

- SoftwareGuide/Latex/Introduction/Installation.tex
Unless special precautions are taken, as done with the ITK Python wrapping,
linking static libraries multiple times into binaries used in the same
executable can cause issues due to duplicate global variables, like the
GlobalTimeStamp or the ObjectFactory.
Change-Id: I761deb8361d94c38d4028c5d8f6c6780bd98b863
CC: @jjomier
> DOC: Warn against linking static libraries multiple times.

- CMakeLists.txt
- SoftwareGuide/CMakeLists.txt
- SoftwareGuide/Cover/Source/CMakeLists.txt
- SoftwareGuide/Examples/CMakeLists.txt
- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
- SoftwareGuide/Latex/Introduction/Installation.tex
Require CMake minimum version to be 3.9.5 following ITKv5 requiring
C++11:
https://discourse.itk.org/t/minimum-cmake-version-update/585
Change-Id: Id29122ae88d449854fb22aea0048224e9025d85c
> ENH: Require cmake minimum version to be 3.9.5.

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
- SoftwareGuide/Latex/Introduction/Installation.tex
- SoftwareGuide/Latex/Introduction/Introduction.tex
Update the link to join the mailing list to directly point at the
[ITK discussion](https://discourse.itk.org/).
Provide a short explanation about the transition from the mailing list to
[Discourse](https://www.discourse.org/).
Prefer `ITK dicussion` to `mailing list`.
Update the section header and the corresponding labels to better reflect
the change.
Resolves #22
Change-Id: I435161457e1f622c4492cc715c4efcd48ef3284d
> DOC: Update the ITK mailing list to point to discourse.

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Use the right label to cross-ref to the `KWStyle` section.
Change-Id: Ie7bfd326a6b07a172a65efa29ea996cf8a6ac1f9
> BUG: Fix missing cross-refs.

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Following the discussion in
https://discourse.itk.org/t/noncopyable/648
and the patch sets:
http://review.source.kitware.com/#/c/23289/
http://review.source.kitware.com/#/c/23294/
move the `ITK_DISALLOW_COPY_AND_ASSIGN` macro to the public section of a
class in the `Coding Style Guide` chapter.
Also, add an explanation about it in the `Using Standard Macros`
section.
> DOC: Move the ITK_DISALLOW_COPY_AND_ASSIGN to public section.

- SoftwareGuide/Latex/DevelopmentGuidelines/WriteAFilter.tex
Add missing period to ie.: i.e.
> DOC: Add the correct punctuation to i.e.

- SoftwareGuide/Latex/Introduction/Introduction.tex
Fix the missing text from the *Introduction* due to a `\emph{}`
environment being split across lines.
Fixes #70.
> BUG: Fix the introduction text missing from the output PDF file.

- SoftwareGuide/Latex/04-Contributors.tex
Remove the references to hybrid segmentation methods from the
`Contrbutors` section.
The hybrid segmentation methods (namely the
`itk::SimpleFuzzyConnectedness*` filters and also possibly
`itk::VectorFuzzyConnectednessImageFilter`) were ruled out from ITK due
to patent issues as of ITKv4.
The commit that removed them:
https://github.com/InsightSoftwareConsortium/ITK/commit/6a61bb88493735815d469c144b5b707eb4c93b29
The ITKv4 release notes that notified about it:
https://itk.org/Wiki/ITK/Release_4/Removed_or_renamed_classes
and
https://itk.org/Wiki/ITK_Release_4/Migration_Plan/Release_Notes/ITKv4_Final_Release_Notes
and
https://itk.org/Wiki/ITK/Release_4/Migration_Plan/Release_Notes
> DOC: Remove refs to hybrid segmentation methods (patent issues).

- SoftwareGuide/Latex/00-Preamble-Common.tex
Fix the missing escape character to write accents in the PDF document
properties.
> DOC: Fix typos in PDF document properties.

- CMakeLists.txt
- SoftwareGuide/CMakeLists.txt
- SoftwareGuide/Cover/Source/CMakeLists.txt
- SoftwareGuide/Examples/CMakeLists.txt
- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
As agreed in:
https://discourse.itk.org/t/cmake-update/870/
Set the `cmake_minimum_required` to version **3.10.2**.
> COMP: Set the minimum required CMake version to 3.10.2.

- SoftwareGuide/Latex/Introduction/Introduction.tex
Fix hyperlink bugs introduced by commit 1298dcb in the `The Insight
Community and Support` section: the text of the hyperlink comes after
the URL in the LaTeX `href` command.
> BUG: Fix hyperlink bugs in Community and Support section.

- SoftwareGuide/Latex/04-Contributors.tex
- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Fix some minor ortography mistakes:
- Add a white space after a punctuation sign.
- Remove a spare white space after forward slash between two words (was
a matter of LaTeX adding a white space for broken lines).
> DOC: Fix some minor ortography mistakes.

- SoftwareGuide/Latex/Introduction/Installation.tex
The compiler list time schedule in chapter `Configuring and Building
ITK` was being displayed with an awkward layout.
See for example p.10 in a recent build belonging to PR #64:
https://open.cdash.org/upload/8fc8cf811a130b76f66c2b81a3f3027ac17e3b09/ITKSoftwareGuide-Book1.pdf
As explained in:
https://en.wikibooks.org/wiki/LaTeX/Mathematics
the `\[` is a LaTeX shorthand for a displayed equation environment.
This topic removes the unnecessary backward slash escape character.
> BUG: Fix compiler list time schedule format.

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Set the preferred Doxygen documentation style explicityle following the
discussion in:
http://review.source.kitware.com/#/c/23399/
> ENH: Set the preferred Doxygen documentation style explictly.

- SoftwareGuide/Latex/Introduction/Installation.tex
Fix `Table 2.1` in chapter `CONFIGURING AND BUILDING ITK` exceeding the
page width.
Fixes #62.
> BUG: Fix Table 2.1 exceeding the page width.

- Utilities/GitSetup/git-pr
The response can be:
{'message': "API rate limit exceeded for 97.65.134.139. (But here's the good
news: Authenticated requests get a higher rate limit. Check out the
documentation for more details.)", 'documentation_url':
'https://developer.github.com/v3/#rate-limiting'}
> BUG: Fail gracefully in git-pr with too many requests

- SoftwareGuide/Examples/ParseCxxExamples.py
`RunExamples` has been moved from `ITKSoftwareGuide/SoftwareGuide/Examples`
to a CMake `ExternalProject_Add`. This means that the subfolder
`ITKSoftwareGuide/SoftwareGuide/Examples` is not created a configure time
anymore. When Examples are parsed to be converted to `tex` files, the parser
fails to write the generated `tex` file as the output folder does not
exist.
> BUG: Missing binary Examples folder

- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
- SoftwareGuide/Latex/Introduction/Installation.tex
Add documentation to
- Show how to use CMake command-line tool.
- Show how to use ITK as an external library.
- How to contribute with a remote module.
In the latter case, many ITK wiki contents were re-used:
https://itk.org/Wiki/ITK/Policy_and_Procedures_for_Adding_Remote_Modules
Addresses:
https://insightsoftwareconsortium.atlassian.net/projects/ITK/issues/ITK-3211?filter=myopenissues
> DOC: Add documentation about command-line CMake and Remote Modules.

- SoftwareGuide/Latex/Introduction/Introduction.tex
Footnote 2 on page 4 of the current ITK Software Guide PDF version
available at:
https://itk.org/ItkSoftwareGuide.pdf
refers to `Section 2.1. Obtaining the Software`. However, the footnote
only displays the section number `2.1`.
This patch set makes LaTeX display the section name, and also adds
additional information to make it clear that it refers to a resource
within the file itself.
> ENH: Make the section name appear in footnote 2 .

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- SoftwareGuide/Latex/README.md
Add a section for writing examples used in the ITK Software Guide.
Although some overlap exists with the
[LaTeX README.md file](https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/master/SoftwareGuide/Latex/README.md),
this was motivated by the constant build failures reported by CI builds,
and addressed for this time in:
http://review.source.kitware.com/#/c/23473/1
Also, emphasize the column limit in the mentioned `README` file.
> DOC: Add a section for SW Guide example writing.

- SoftwareGuide/Latex/DevelopmentGuidelines/WriteAFilter.tex
The copy constructor and assignment operators must be declared in the
public section. See discussion in:
https://discourse.itk.org/t/itk-disallow-copy-and-assign/648?page=2
> DOC: Fix copy constructor and assignment operator section.

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Add the symbol export documentation following the discussion in:
https://discourse.itk.org/t/correct-usage-of-export-macros/1304/1
> DOC: Add the symbol export documentation.

- Utilities/GitSetup/git-review-push
GitHub now provides a similar server-side hook with a link to open the
PR.
> ENH: Remove pull request preview link for git review-push

- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
Change vestigial `Gerrit` references to `GitHub` after the migration has
been completed.
> DOC: Change `Gerrit` references to `GitHub`.

- SoftwareGuide/Latex/DesignAndFunctionality/Registration.tex
The set of transforms which include the center as an optimization
parameter have proven to be poor for optimizer based registration and
are not recommend to be used. Therefor, the section has been refocused
on the importance of initializing the center of a transform instead.
> ENH: Relabel subsection to "Center Initialization"

- SuperBuild/External_ITK.cmake
Brings in
https://github.com/InsightSoftwareConsortium/ITK/pull/379/commits/7278a0f2a6ba046a35099b70d6ace9d85b7cb24d
> COMP: Bump ITK to avoid example line length warnings

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Ensure we have a newline in the test output.
> BUG: Add missing newline to Test finished notice

- SoftwareGuide/Latex/Introduction/Installation.tex
The Cygwin compiler is no longer supported -- we now support Mingw-w64.
@maekclena please take a look.
Addresses #116
> DOC: Update references to Cygwin

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
Update ITK testing macros names after they were renamed in
https://github.com/InsightSoftwareConsortium/ITK/pull/999
> DOC: Update ITK testing macros names

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Fix testing macro name: `TEST_SET_GET_OBJECT` does not exist as a testing
macro (or as any other macro in ITK).
> DOC: Fix testing macro name

- SoftwareGuide/Latex/Architecture/SpatialObjects.tex
Detail that GroupSpatialObject in ITKv5 replaces SceneSpatialObject,
and retains nearly identical functionality.
There is a corresponding pull request in ITK: https://github.com/InsightSoftwareConsortium/ITK/pull/1005.
> DOC: Clarifies that GroupSO replaces SceneSO

- SoftwareGuide/Latex/Introduction/Installation.tex
As noted earlier in the paragraph, we now mimick the Visual Studio
support lifecycle, so removing the supported years.
ITK 5.0 and later requires Visual Studio 2015 and later for C++11
support.
At the time of this writing, Visual Studio 2019 does not work with
standard compiler flags per the discussion here:
https://discourse.itk.org/t/has-anyone-tried-to-build-visual-studio-c-2019/1561/11
> DOC: Update supported Visual Studio versions

- .circleci/config.yml
This is now limited to paid plans.
> BUG: Remove CircleCI resource_class specification

- Utilities/GitSetup/config
The GitSetup repo on public.kitware.com will be removed.
> ENH: Point GitSetup to ITK repository

- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
Add missing table borders in `How To Create A Module` chapter.
> ENH: Add missing table borders in `How To Create A Module` chapter

- SoftwareGuide/Latex/Introduction/Installation.tex
- SoftwareGuide/Latex/Introduction/Introduction.tex
Miscellaneus fixes in the `Introduction` and `Installation` chapters:
- Fix the development environment names.
- Rework the compiler list: update to currently supported versions.
- Remove the compiler support/deprecation cycle table due to difficulties
in keeping it up to date.
- Remove the deprecated reference to the Wiki Examples: examples are
entirely hosted in https://itk.org/ITKExamples/ since a series of PRs
including
InsightSoftwareConsortium/ITKExamples#108 and
InsightSoftwareConsortium/ITKExamples#109.
- Update the `vxl` link.
- Fix the `Utilities` and `Wrapping` parent folders.
- Mention the raw binary files and the SHA512 hash files in the `Testing`
folder paragraph.
- Take advantage of the commit to order alphabetically the ITK's main
folders.
Take advantage of the commit for …
> ENH: Miscellaneous fixes in introduction and installation

- README.md
Point `build` CI badge to builds: point to the master branch status by
default.
> ENH: Point `build` CI badge to builds

- .hooks-config.bash
- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
- Utilities/Hooks/commit-msg
- Utilities/Hooks/pre-commit
- Utilities/Hooks/prepare-commit-msg
- Utilities/SetupForDevelopment.sh
As part of the process of the Insight Software Consortium joining the
NumFOCUS non-profit corporation as a Fiscally Sponsored Project, all
assets, including intellectual property assets, are being transferred to
enable dissolution of the Insight Software Consortium non-profit
corporate legal entity.
The Insight Software Consortium Board of Directors resolved in the
2019-10-22 Meeting to assign ITK copyright to NumFOCUS and CMake and
IGSTK to Kitware. A copy of the signed copyright transfer documents can be
found in the corresponding pull request to ITK:
https://github.com/InsightSoftwareConsortium/ITK/pull/1598
> DOC: Update copyright assignment to NumFOCUS

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
Adapt section about enums to the adoption of strongly typed enums in ITK:
https://github.com/InsightSoftwareConsortium/ITK/commit/0dd31a62f851a0ae95ef4c6d6c85e531a4ebca59
Fixes #154 .
> DOC: Adapt enum section to strongly typed enums

- SoftwareGuide/Latex/Introduction/Installation.tex
Following pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2563
"ENH: Upgrade ITK from C++11 to C++14"
Suggested by Jon Haitz Legarreta Gorroño (@jhlegarreta) at https://github.com/InsightSoftwareConsortium/ITK/pull/2563/#issuecomment-852134729
> ENH: Update compiler versions for C++14

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Use `itkNameOfTestExecutableMacro` macro to retrieve the test name.
> STYLE: Use `itkNameOfTestExecutableMacro` macro for test names

- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
Add `long long` specifier C++ and mangling types.
> DOC: Add `long long` specifier C++ and mangling types

- .github/labeler.yml
- .github/workflows/label-pr.yml
Add labeler workflow so that a `GitHub` action, triggered when a PR is
opened, automatically labels the PR based on the given rules.
> ENH: Add labeler workflow

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Print backslash mark.
Fixes:
```
Note that ITK prefers the backslash ("
") style versus the at-sign (“@”) style to write the documentation command
```
and
```
When documenting a class header, if citations are required, use the Doxygen
`par References` command to list the references in a separate and
clearly visible paragraph
```
Use the `code` command for the at-sign as well for the sake of
consistency.
> DOC: Print backslash mark

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- DOC: Fix Doxygen special command markup and provide example 
- DOC: Fix Doxygen link
> ENH: Fix Doxygen documentation paragraph

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- DOC: Remove uses of itk::ImageTraits 
- DOC: Make test ending messages consistent  
- DOC: Override destructor and prefer = default for trivial bodies
- DOC: Match the current function deletion practice in ITK 
- DOC: Prefer using pre-increment over post-increment 
- DOC: Update the ITK code style to current automatically enforced 
- DOC: Document brace and brace list initialization preference
- DOC: Update `itk::N4BiasFieldCorrectionImageFilter::Sharpen` definition
Fixes #133.
> ENH: Update coding style guidelines

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
The .h files include the .hxx files, which in
turn include the original .h file.
Remove the recursive includes.
Following the change in ITK:
https://github.com/InsightSoftwareConsortium/ITK/pull/2958/commits/eec896842c1e4a54f4e894c2b3600b83279fd5ff
> DOC: Remove recursive inclusion of .h files

- CMake/ITK_CheckCCompilerFlag.cmake
- SoftwareGuide/Cover/Source/ModelBasedSegmentation.cxx
- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Following ITK commits:
"STYLE: removing void if used in place of empty parameter list"
by Dženan Zukić (@dzenanz), 11 September 2018
https://github.com/InsightSoftwareConsortium/ITK/commit/60807f4abcfd7c4d42ddf93796d6acf272aa442b
"STYLE: Remove redundant void argument lists"
by Hans Johnson (@hjmjohnson), 20 February 2020
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/1628
https://github.com/InsightSoftwareConsortium/ITK/commit/e6d859ecae955a4e2a44b9e60677093dc254a4ca
In accordance with C++ Core Guidelines, August 19, 2021:
"Don't use void as an argument type"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl25-dont-use-void-as-an-argument-type
Clang-Tidy "modernize-redundant-void-arg" check:
https://clang.llvm.org/extra/clang-tidy/checks/modernize-redunda …
> STYLE: Do not use `void` in empty function parameter list

- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
Add subsection for discussion of ITK Python debugging workflow based on @brad-t-moore 's internal presentation and upcoming blog post.
> DOC: Add section on debugging Python wrappings

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Adds a guideline in accordance with commit https://github.com/InsightSoftwareConsortium/ITK/commit/c54ad6715a68570f9db14f002c239ec7ea06383d
"COMP: Use trailing return type instead of typename + dependent type"
Discussed at pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2780
"Workaround VS2017 compile errors using-declarations"
> ENH: Add "Trailing Return Types" section

- .clang-format
- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- SoftwareGuide/Latex/Appendices/GitWorkflow.tex
- SoftwareGuide/Latex/Architecture/Iterators.tex
- SoftwareGuide/Latex/Architecture/SystemOverview.tex
- SoftwareGuide/Latex/DesignAndFunctionality/ImageInterpolators.tex
- SoftwareGuide/Latex/DevelopmentGuidelines/CreateAModule.tex
- SoftwareGuide/Latex/DevelopmentGuidelines/WriteAFilter.tex
- SoftwareGuide/Latex/Introduction/Installation.tex
Update several code snippets in the document to conform to our current `clang-format`.
This is DRAFT at first to check for line-length issues and other formatting.
> Clang format of doc

- .github/workflows/build.yml
Switch Github Actions Linux environment version to `ubuntu-20.04`.
`ubuntu-18.04` is being deprecated and support will end by 12/1/2022:
https://github.com/actions/virtual-environments/issues/6002
Related to recent warnings in the Azure Pipelines Linux environment
being used in the main ITK repository:
https://github.com/InsightSoftwareConsortium/ITK/pull/3554/commits/497c3a7b8e1397ca56a2675ce846dca657af8861
> ENH: Switch Github Actions Linux environment

- .github/labeler.yml
Fix the `Documentation`PR title identification: avoid having two entries for the `area:Documentation` label, and use the newly created `type:Documentation` for the PR title regex.
> ENH: Fix the `Documentation` PR title identification

- .github/workflows/build.yml
Update Python version in GitHub Actions to 3.9: Python 3.7 will be deprecated on 27 Jun 2023:
https://endoflife.date/python
Make the version consistent with the version used in the ITK Python wrapping Azure Pipelines CI, and the ITK Sphinx Examples.
> ENH: Update Python version in GitHub Actions to 3.9

- .github/workflows/build.yml
- ENH: Fix workflow actions warnings linked to `Node.js` 
- ENH: Bump `actions/upload-artifact` action to v3
> ENH: Fix workflow actions warnings linked to `Node.js` 

- .github/workflows/build.yml
Update GitHub Actions Ubuntu environment to version `22.04` in the interest of consistency with the rest of the versions used across ITK.
Change the Python package names:
- Use `python3` instead of `python`
- Use `python3-pygments` instead of `python-pygments`
as the latter no longer exist in Ubuntu `22.04`:
https://packages.ubuntu.com/jammy/python/
> ENH: Update GitHub Actions Ubuntu environment version

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
When a data member is set by a "setter" member function (`Set##name`, `On`, or `Off`), it is still recommended to initialize the member according to this guideline. Doing so prevents problems like the one addressed by pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3845 commit https://github.com/InsightSoftwareConsortium/ITK/commit/a31e8bf32a5ebe522e367976227cb4bda84f45e9 "BUG: Fix uninitialized value ImageRegistrationMethodv4::m_NumberOfLevels" by Jon Haitz Legarreta Gorroño (@jhlegarreta), 10 January 2023
> DOC: Remove mistaken exception to data member initialization guideline

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Excluded padding data, `std::unique_ptr`, `itk::SmartPointer` and low level
utility classes from the guideline that says that "all member variables must be
initialized when they are declared".
`std::unique_ptr` and `itk::SmartPointer` are excluded because of some GCC
compile errors, which were addressed in ITK by Simon Rit (@SimonRit):
- pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3877
commit https://github.com/InsightSoftwareConsortium/ITK/commit/eac289d25221d8e080a0ad6d2e6ce6ff0a2c576a
"COMP: Remove in-class {} member initializers of unique_ptr"
- pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3927
commit https://github.com/InsightSoftwareConsortium/ITK/commit/f5f83678755319e35c225bfe563fb26ef1d0197e
"COMP: Remove in class init of SmartPointer …
>  DOC: Adjust initialization rule for padding data, smart pointers, etc.

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Dropped the requirement to use NumericTraits for all numeric data member initialization.
Following pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3950 by Hans Johnson (@hjmjohnson).
> DOC: Do not require using NumericTraits, replace ZeroValue() with `{}`

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Added coding style guidelines for specifying built-in integer types and
integer types from the C library.
Following recent ITK commits, authored by Lee Newberg (@Leengit):
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3365
commit https://github.com/InsightSoftwareConsortium/ITK/commit/8c2c654f3deb8897f22cf9bbce5df3c6482f9a82
commit https://github.com/InsightSoftwareConsortium/ITK/commit/e03a94119d056c6e66365e59e17317d62e339102
"STYLE: Drop `signed` and `int` from some types"
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3139
commit https://github.com/InsightSoftwareConsortium/ITK/commit/a812aa3cefc453a65d493752c186ce2fdc1a7a7d
"STYLE: Change unsigned to unsigned int."
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3250
commit …
> DOC: Add "Integer Type Specifiers" section

- SoftwareGuide/Latex/Introduction/Installation.tex
This follows changes in the main repository, described in this commit: https://github.com/InsightSoftwareConsortium/ITK/commit/45407f3560d91af247c95a1f48d21cbbb8ff6b8d
> Update supported compiler versions to C++17

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Avoid documenting ivar default values since:
- All ivar values should be initialized to some default value.
- When default values are changed, it is easy to forget about updating the documentation and making it inconsistent with the actual value in the code.
> DOC: Avoid documenting ivar default values

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Avoid using initialization lists in coding style code snippets: initialization lists are not encouraged as per current ITK style guidelines.
Similarly, avoid using a boolean ivar setter method in the constructor, as ivars should be initialized when they are declared.
> DOC: Avoid using initialization lists in coding style snippets

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Use non-boolean, built-in ivar type ivars to illustrate the `PrintSelf` method, as the style for printing boolean ivars is not yet consistent across the ITK code base.
> DOC: Use non-boolean, built-in type ivars to illustrate `PrintSelf`

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
Do not encourage using empty comment lines.
Take advantage of the commit to reword the example comment, removing unnecessary wording.
> DOC: Do not encourage using empty comment lines

- SoftwareGuide/Cover/Source/ModelBasedSegmentation.cxx
- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- SoftwareGuide/Latex/DevelopmentGuidelines/WriteAFilter.tex
Following ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4373/ commit https://github.com/InsightSoftwareConsortium/ITK/commit/2c264ea2ef62e916c6ef947599ce659cc8fce5fe "STYLE: Replace itkTypeMacro calls with `itkOverrideGetNameOfClassMacro`"
> DOC: Replace `itkTypeMacro` with `itkOverrideGetNameOfClassMacro`

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- Suggested by Jon Haitz Legarreta Gorroño (@jhlegarreta) at
https://github.com/InsightSoftwareConsortium/ITK/pull/5024#issuecomment-2531648916
> ENH: Add section "Initializing variables of fixed size array types"

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- Addressed the comments by Jon Haitz Legarreta Gorroño (@jhlegarreta) at https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/pull/216#pullrequestreview-2511975124
Specifically:
> `{}` will not highlight the content in LaTeX as you would expect in Markdown:
> LaTex uses double backticks at the beginning/upright ticks at the end for
> ticks, simple backticks will render as opening simple ticks both at the
> beginning/end.
> COMP: Replace backticks with `\code{}` in Initialization and Assignment

- SoftwareGuide/Latex/Introduction/Installation.tex
> DOC: Update supported compiler version information

- SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex
- As suggested by  Jon Haitz Legarreta Gorroño (@jhlegarreta) at https://github.com/InsightSoftwareConsortium/ITK/issues/4645#issuecomment-2610412940
> DOC: Describe `ITK_DEFAULT_COPY_AND_MOVE`

- SoftwareGuide/Latex/Architecture/DataRepresentation.tex
- SoftwareGuide/Latex/Architecture/Iterators.tex
- SoftwareGuide/Latex/Architecture/SystemOverview.tex
> DOC: Spelling corrections

- SoftwareGuide/Art/ImageRegistration1TraceMetric.eps
- SoftwareGuide/Art/ImageRegistration1TraceTranslations.eps
- SoftwareGuide/Art/ImageRegistration4TraceMetric.eps
- SoftwareGuide/Art/ImageRegistration4TraceTranslations.eps
- SoftwareGuide/Art/ImageRegistration4TraceTranslations2.eps
- SoftwareGuide/Art/ImageRegistration5TraceAngle1.eps
- SoftwareGuide/Art/ImageRegistration5TraceAngle2.eps
- SoftwareGuide/Art/ImageRegistration5TraceMetric1.eps
- SoftwareGuide/Art/ImageRegistration5TraceMetric2.eps
- SoftwareGuide/Art/ImageRegistration5TraceTranslations1.eps
- SoftwareGuide/Art/ImageRegistration5TraceTranslations2.eps
- SoftwareGuide/Art/ImageRegistration6TraceAngle.eps
- SoftwareGuide/Art/ImageRegistration6TraceMetric.eps
- SoftwareGuide/Art/ImageRegistration6TraceTranslations.eps
- SoftwareGuide/Art/ImageRegistration7TraceAngle.eps
- SoftwareGuide/Art/ImageRegistration7TraceMetric.eps
- SoftwareGuide/Art/ImageRegistration7TraceScale.eps
- SoftwareGuide/Art/ImageRegistration7TraceTranslations.eps
- SoftwareGuide/Art/ImageRegistration8TraceAngle.eps
- SoftwareGuide/Art/ImageRegistration8TraceMetric.eps
- SoftwareGuide/Art/ImageRegistration8TraceTranslations.eps
- SoftwareGuide/Art/ImageRegistration9TraceAngle.eps
- SoftwareGuide/Art/ImageRegistration9TraceMetric.eps
- SoftwareGuide/Art/ImageRegistration9TraceTranslations.eps
- SoftwareGuide/Art/MultiResImageRegistration1TraceMetric.eps
- SoftwareGuide/Art/MultiResImageRegistration1TraceTranslations.eps
Fix the PDF file properties: set the `SupressPDFMark` variable to `true` in the `eps` files.
The properties of the eps figures generated by gnuplot at the time the PDF is generated were ovewriting the LaTeX `hyperref` settings of the book, effectively modifying the title, author, subject, and keywords of the PDF file.
Relevant thread:
https://groups.google.com/g/comp.graphics.apps.gnuplot/c/WTjwj-lbC90
> DOC: Fix PDF file properties in Book 2

- SoftwareGuide/Latex/ITKSoftwareGuide-Book1.tex
Adding appendices properly to bookmarks. Closes #128.
> DOC: Appendices bookmarks not being generated
